kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dv-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: lars-sandbox
roleRef:
  kind: ClusterRole
  name: dv-reader
  apiGroup: rbac.authorization.k8s.io
