apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: centos-8-stream
spec:
  source:
    http:
      url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2
  storage:
    resources:
      requests:
        storage: 10Gi
